### Verificar servidor
GET http://localhost:3001/health

### Criar um encontro
POST http://localhost:3001/encounters
Content-Type: application/json

{
  "name": "Emboscada na Floresta",
  "description": "Orcs atacam o grupo no caminho para Triel"
}

### Buscar encontro (substitui o ID depois de criar)
GET http://localhost:3001/encounters/cmpvgtdxb0000c2d4g9oe38u6



### Adicionar monstro ao encontro
POST http://localhost:3001/encounters/cmpvgtdxb0000c2d4g9oe38u6/combatants
Content-Type: application/json

{
  "name": "Orc Guerreiro",
  "initiative": 12,
  "hpMax": 15,
  "ac": 13,
  "isPlayer": false
}

### Adicionar jogador ao encontro
POST http://localhost:3001/encounters/cmpvgtdxb0000c2d4g9oe38u6/combatants
Content-Type: application/json

{
  "name": "Dan",
  "initiative": 18,
  "hpMax": 28,
  "ac": 15,
  "isPlayer": true
}

### Iniciar o combate
POST http://localhost:3001/encounters/cmpvgtdxb0000c2d4g9oe38u6/start

### Passar o turno
POST http://localhost:3001/encounters/cmpvgtdxb0000c2d4g9oe38u6/next-turn